### PR TITLE
Add iOS support

### PR DESCRIPTION
**Pull request by mfkl**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@mfkl you are awesome. I will get to this one tonight

BTW did u want to be a core maintainer of this project? TBH it is not very much work. but it would be good to have someone else on the project

**Comment by mfkl** [comment]
> @mfkl you are awesome. I will get to this one tonight

Code is already out there, I take no credit for this.

> BTW did u want to be a core maintainer of this project? TBH it is not very much work. but it would be good to have someone else on the project

Sure, if that helps you.

**Comment by SimonCropp** [comment]
whats your nuget id? also did u want to sign up for tidelift?

**Comment by mfkl** [comment]
https://www.nuget.org/profiles/mfkl

I'm not sure about tidelift or what that entails yet.

**Pull request merged**
